### ISSUE TITLE
Realsense d435i crashing occasionally 

### ISSUE THREAD

**Issue by ivelso** [realsenseai/realsense-ros#1407]
Realsense d435i
Turtlebot3 with intel nuc with ubuntu 16.04
ROS kinetic 1.12.14

The camera can run for a while and then suddenly crash, with the need of disconnecting the camera in order to make it work again.   
The camera frequency is reduced to 15fps in order to receive the images on a remote computer as it was not received any images when using 30fps. Still, a lot of the images are lost but this might be because of transmission between to computers. 
Is it anything to do in order to make the camera more reliable and make it not crash? 

It is also saying  Hardware Notification:USB SCP overflow. The usb should be a usb 3 as it is colored blue but it seems as it is functioning as usb2. The camera is connected using the original cable. 

This is a log of the output from the realsense node: 
 
turtlebot07@turtlebot07:~$ roslaunch turtlebot3_bringup turtlebot3_robot.launch 
... logging to /home/turtlebot07/.ros/log/9eda4a1a-fb1c-11ea-94f8-0800274146ea/roslaunch-turtlebot07-15401.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.0.17:33611/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 30
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -1.0
 * /camera/realsense2_camera/color_fps: 15
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 15
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 15
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 30
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 15
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: False
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: camera/odom_in
 * /camera/realsense2_camera/unite_imu_method: none
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /turtlebot3_core/baud: 115200
 * /turtlebot3_core/port: /dev/ttyACM0
 * /turtlebot3_core/tf_prefix: 
 * /turtlebot3_lds/frame_id: base_scan
 * /turtlebot3_lds/port: /dev/ttyUSB0

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)
  /
    turtlebot3_core (rosserial_python/serial_node.py)
    turtlebot3_diagnostics (turtlebot3_bringup/turtlebot3_diagnostics)
    turtlebot3_lds (hls_lfcd_lds_driver/hlds_laser_publisher)

ROS_MASTER_URI=http://192.168.0.112:11311

process[turtlebot3_core-1]: started with pid [15410]
process[turtlebot3_lds-2]: started with pid [15411]
process[camera/realsense2_camera_manager-3]: started with pid [15412]
process[camera/realsense2_camera-4]: started with pid [15413]
process[turtlebot3_diagnostics-5]: started with pid [15415]
[ INFO] [1600592124.271912368]: Initializing nodelet with 4 worker threads.
[ INFO] [1600592124.400607782]: RealSense ROS v2.2.13
[ INFO] [1600592124.400648215]: Running with LibRealSense v2.34.0
[ INFO] [1600592124.492896962]:  
[INFO] [1600592124.509252]: ROS Serial Python Node
[INFO] [1600592124.548143]: Connecting to /dev/ttyACM0 at 115200 baud
 20/09 18:55:24,570 WARNING [139927824013056] (types.cpp:49) hwmon command 0x4f failed.
Error type: No data to return (-21).
 20/09 18:55:24,570 WARNING [139927824013056] (ds5-motion.cpp:464) IMU Calibration is not available, see the previous message
[ INFO] [1600592124.572652719]: Device with serial number 841612071764 was found.

[ INFO] [1600592124.572715712]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-4/2-4:1.0/video4linux/video0 was found.
[ INFO] [1600592124.572756847]: Device with name Intel RealSense D435I was found.
[ INFO] [1600592124.573586298]: Device with port number 2-4 was found.
[ INFO] [1600592124.602929231]: getParameters...
[ INFO] [1600592125.710177092]: setupDevice...
[ INFO] [1600592125.710299668]: JSON file is not provided
[ INFO] [1600592125.710361731]: ROS Node Namespace: camera
[ INFO] [1600592125.710503897]: Device Name: Intel RealSense D435I
[ INFO] [1600592125.710718961]: Device Serial No: 841612071764
[ INFO] [1600592125.710805189]: Device physical port: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-4/2-4:1.0/video4linux/video0
[ INFO] [1600592125.710891188]: Device FW version: 05.12.07.100
[ INFO] [1600592125.710989534]: Device Product ID: 0x0B3A
[ INFO] [1600592125.711075931]: Enable PointCloud: Off
[ INFO] [1600592125.711136860]: Align Depth: On
[ INFO] [1600592125.711203249]: Sync Mode: On
[ INFO] [1600592125.711517790]: Device Sensors: 
[ INFO] [1600592125.711720161]: Stereo Module was found.
[ INFO] [1600592125.711837503]: RGB Camera was found.
[ INFO] [1600592125.711925392]: Motion Module was found.
[ INFO] [1600592125.712056195]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1600592125.712095629]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1600592125.712131636]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1600592125.712172709]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1600592125.712238855]: num_filters: 0
[ INFO] [1600592125.712302660]: Setting Dynamic reconfig parameters.
[ INFO] [1600592126.293206047]: Done Setting Dynamic reconfig parameters.
[ INFO] [1600592126.312512734]: depth stream is enabled - width: 640, height: 480, fps: 15, Format: Z16
[ INFO] [1600592126.342027635]: color stream is enabled - width: 640, height: 480, fps: 15, Format: RGB8
[ INFO] [1600592126.343375158]: setupPublishers...
[ INFO] [1600592126.371100012]: Expected frequency for depth = 15.00000
[INFO] [1600592126.676546]: Note: publish buffer size is 1024 bytes
[INFO] [1600592126.677575]: Setup publisher on sensor_state [turtlebot3_msgs/SensorState]
[INFO] [1600592126.688479]: Setup publisher on firmware_version [turtlebot3_msgs/VersionInfo]
[INFO] [1600592126.721198]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1600592126.730340]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[ INFO] [1600592126.735068639]: Expected frequency for color = 15.00000
[INFO] [1600592126.748489]: Setup publisher on odom [nav_msgs/Odometry]
[INFO] [1600592126.758902]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1600592126.773240]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1600592126.787461]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[ INFO] [1600592127.064836143]: Expected frequency for aligned_depth_to_color = 15.00000
[INFO] [1600592127.218879]: Setup publisher on /tf [tf/tfMessage]
[INFO] [1600592127.234696]: Note: subscribe buffer size is 1024 bytes
[INFO] [1600592127.235292]: Setup subscriber on cmd_vel [geometry_msgs/Twist]
[INFO] [1600592127.254532]: Setup subscriber on joint_trajectory_point [std_msgs/Float64MultiArray]
[INFO] [1600592127.274743]: Setup subscriber on joint_move_time [std_msgs/Float64]
[INFO] [1600592127.295768]: Setup subscriber on gripper_position [std_msgs/Float64MultiArray]
[INFO] [1600592127.318735]: Setup subscriber on gripper_move_time [std_msgs/Float64]
[INFO] [1600592127.335454]: Setup subscriber on sound [turtlebot3_msgs/Sound]
[INFO] [1600592127.365226]: Setup subscriber on motor_power [std_msgs/Bool]
[INFO] [1600592127.390352]: Setup subscriber on reset [std_msgs/Empty]
[ INFO] [1600592127.431726935]: setupStreams...
[ INFO] [1600592127.433395285]: insert Depth to Stereo Module
[ INFO] [1600592127.433610792]: insert Color to RGB Camera
[ INFO] [1600592127.471210060]: SELECTED BASE:Depth, 0
[ INFO] [1600592127.634435272]: RealSense Node Is Up!
 20/09 18:55:27,934 ERROR [139927807227648] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs)
 20/09 18:55:28,136 ERROR [139927807227648] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs)
 20/09 18:55:28,338 ERROR [139927807227648] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs)
 20/09 18:55:28,539 ERROR [139927807227648] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs)
 20/09 18:55:29,394 ERROR [139927807227648] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs)
[INFO] [1600592129.793999]: Setup TF on Odometry [odom]
[INFO] [1600592129.795725]: Setup TF on IMU [imu_link]
[INFO] [1600592129.797484]: Setup TF on MagneticField [mag_link]
[INFO] [1600592129.799203]: Setup TF on JointState [base_link]
[INFO] [1600592129.812297]: --------------------------
[INFO] [1600592129.814053]: Connected to OpenCR board!
[INFO] [1600592129.815680]: This core(v2.0.1) is compatible with TB3 with OpenManipulator
[INFO] [1600592129.817323]: --------------------------
[INFO] [1600592129.819041]: Start Calibration of Gyro
[INFO] [1600592132.360976]: Calibration End
[ WARN] [1600592132.427648213]: This firmware(v2.0.1) isn't compatible with this software (v1.2.3)
[ WARN] [1600592132.427790139]: You can find how to update its in `FAQ` section(turtlebot3.robotis.com)
20/09 19:37:00,235 ERROR [139927782049536] (types.h:307) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 20/09 19:37:00,235 ERROR [139927782049536] (error-handling.cpp:68) Error during polling error handler: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 20/09 19:37:00,238 ERROR [139927644702464] (types.h:307) xioctl(VIDIOC_DQBUF) failed for fd: 14 Last Error: No such device
 20/09 19:37:00,238 ERROR [139927644702464] (backend-v4l2.cpp:1310) xioctl(VIDIOC_DQBUF) failed for fd: 14 Last Error: No such device
[ WARN] [1600594620.238791007]: Hardware Notification:xioctl(VIDIOC_DQBUF) failed for fd: 14 Last Error: No such device,1.60059e+12,Error,Unknown Error
 20/09 19:37:00,241 ERROR [139927633835776] (types.h:307) xioctl(VIDIOC_DQBUF) failed for fd: 21 Last Error: No such device
 20/09 19:37:00,241 ERROR [139927633835776] (backend-v4l2.cpp:1310) xioctl(VIDIOC_DQBUF) failed for fd: 21 Last Error: No such device
[ WARN] [1600594620.241661336]: Hardware Notification:xioctl(VIDIOC_DQBUF) failed for fd: 21 Last Error: No such device,1.60059e+12,Error,Unknown Error
 20/09 19:37:00,245 ERROR [139927807227648] (types.h:307) set_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 20/09 19:37:00,245 ERROR [139927807227648] (global_timestamp_reader.cpp:194) Error during time_diff_keeper polling: set_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 20/09 19:37:01,236 ERROR [139927782049536] (types.h:307) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 20/09 19:37:01,236 ERROR [139927782049536] (error-handling.cpp:68) Error during polling error handler: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 20/09 19:37:01,246 ERROR [139927807227648] (types.h:307) Cannot open '/dev/video0 Last Error: No such file or directory
 20/09 19:37:01,246 ERROR [139927807227648] (global_timestamp_reader.cpp:194) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
[ERROR] [1600594621.925797610]: The device has been disconnected!
 20/09 19:37:02,236 ERROR [139927782049536] (types.h:307) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 20/09 19:37:02,236 ERROR [139927782049536] (error-handling.cpp:68) Error during polling error handler: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 20/09 19:37:02,247 ERROR [139927807227648] (types.h:307) Cannot open '/dev/video0 Last Error: No such file or directory
 20/09 19:37:02,247 ERROR [139927807227648] (global_timestamp_reader.cpp:194) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 20/09 19:37:02,562 ERROR [139927832405760] (types.h:307) xioctl(VIDIOC_STREAMOFF) failed for buf_type=1 Last Error: No such device
 20/09 19:37:02,567 ERROR [139927832405760] (types.h:307) xioctl(VIDIOC_STREAMOFF) failed for buf_type=1 Last Error: No such device
 20/09 19:37:02,569 ERROR [139927832405760] (types.h:307) xioctl(VIDIOC_REQBUFS) failed Last Error: No such device
[ INFO] [1600594627.588823478]: Checking new devices...
[ INFO] [1600594627.588902222]:  
 20/09 19:37:07,610 WARNING [139927832405760] (types.cpp:49) hwmon command 0x4f failed.
Error type: No data to return (-21).
 20/09 19:37:07,610 WARNING [139927832405760] (ds5-motion.cpp:464) IMU Calibration is not available, see the previous message
[ INFO] [1600594627.612308899]: Device with serial number 841612071764 was found.

[ INFO] [1600594627.612438915]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/video4linux/video3 was found.
[ INFO] [1600594627.612516163]: Device with name Intel RealSense D435I was found.
[ INFO] [1600594627.613661501]: Device with port number 1-4 was found.
[ INFO] [1600594627.636464141]: getParameters...
[ INFO] [1600594628.772868154]: setupDevice...
[ INFO] [1600594628.772944535]: JSON file is not provided
[ INFO] [1600594628.773014195]: ROS Node Namespace: camera
[ INFO] [1600594628.773083807]: Device Name: Intel RealSense D435I
[ INFO] [1600594628.773125470]: Device Serial No: 841612071764
[ INFO] [1600594628.773190097]: Device physical port: /sys/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/video4linux/video3
[ INFO] [1600594628.773254060]: Device FW version: 05.12.07.100
[ INFO] [1600594628.773303046]: Device Product ID: 0x0B3A
[ INFO] [1600594628.773341062]: Enable PointCloud: Off
[ INFO] [1600594628.773389036]: Align Depth: On
[ INFO] [1600594628.773433893]: Sync Mode: On
[ INFO] [1600594628.773553301]: Device Sensors: 
[ INFO] [1600594628.773638961]: Stereo Module was found.
[ INFO] [1600594628.773710429]: RGB Camera was found.
[ INFO] [1600594628.773785460]: Motion Module was found.
[ INFO] [1600594628.773847861]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1600594628.773889241]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1600594628.773948809]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1600594628.773999276]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1600594628.774060666]: num_filters: 0
[ INFO] [1600594628.774103731]: Setting Dynamic reconfig parameters.
[ INFO] [1600594629.377570792]: Done Setting Dynamic reconfig parameters.
[ INFO] [1600594629.384071926]: depth stream is enabled - width: 640, height: 480, fps: 15, Format: Z16
[ INFO] [1600594629.394246884]: color stream is enabled - width: 640, height: 480, fps: 15, Format: RGB8
[ INFO] [1600594629.397464327]: setupPublishers...
[ INFO] [1600594629.406700055]: Expected frequency for depth = 15.00000
[ INFO] [1600594629.739670855]: Expected frequency for color = 15.00000
[ INFO] [1600594630.101916013]: Expected frequency for aligned_depth_to_color = 15.00000
[ WARN] [1600594630.379274185]: Hardware Notification:USB SCP overflow,1.60059e+12,Error,Hardware Error
[ INFO] [1600594630.713101510]: setupStreams...
[ INFO] [1600594630.714938417]: insert Depth to Stereo Module
[ INFO] [1600594630.715058161]: insert Color to RGB Camera
 20/09 19:37:10,749 ERROR [139927832405760] (types.h:307) xioctl(VIDIOC_S_FMT) failed Last Error: Input/output error
[ERROR] [1600594630.750359663]: An exception has been thrown: xioctl(VIDIOC_S_FMT) failed Last Error: Input/output error
 20/09 19:37:10,750 ERROR [139927832405760] (context.cpp:427) Exception thrown from user callback handler
[ WARN] [1600594632.381117113]: Hardware Notification:USB SCP overflow,1.60059e+12,Error,Hardware Error
[ WARN] [1600594634.382881076]: Hardware Notification:USB CAM overflow,1.60059e+12,Error,Hardware Error
[ WARN] [1600594635.384166479]: Hardware Notification:USB SCP overflow,1.60059e+12,Error,Hardware Error
 20/09 19:37:15,739 WARNING [139927644702464] (backend-v4l2.cpp:988) Frames didn't arrived within 5 seconds
[ WARN] [1600594636.385420623]: Hardware Notification:USB CAM overflow,1.60059e+12,Error,Hardware Error
[ WARN] [1600594637.386635939]: Hardware Notification:USB SCP overflow,1.60059e+12,Error,Hardware Error
[ WARN] [1600594639.388340851]: Hardware Notification:USB SCP overflow,1.60059e+12,Error,Hardware Error
 20/09 19:37:20,744 WARNING [139927644702464] (backend-v4l2.cpp:988) Frames didn't arrived within 5 seconds
[ WARN] [1600594641.390324915]: Hardware Notification:USB SCP overflow,1.60059e+12,Error,Hardware Error
[ WARN] [1600594643.392083043]: Hardware Notification:USB SCP overflow,1.60059e+12,Error,Hardware Error
[ WARN] [1600594645.393755879]: Hardware Notification:USB SCP overflow,1.60059e+12,Error,Hardware Error
 20/09 19:37:25,746 WARNING [139927644702464] (backend-v4l2.cpp:988) Frames didn't arrived within 5 seconds
[ WARN] [1600594647.395432051]: Hardware Notification:USB SCP overflow,1.60059e+12,Error,Hardware Error
[ WARN] [1600594649.397314628]: Hardware Notification:USB CAM overflow,1.60059e+12,Error,Hardware Error
[ WARN] [1600594650.398528848]: Hardware Notification:USB SCP overflow,1.60059e+12,Error,Hardware Error

**Comment by MartyG-RealSense** [comment]
Hi @ivelso  My first point of advice would be to not use librealsense SDK version 2.34.0 as it had a problem with continuously generating timing errors.   If you wish to keep your currently installed ROS wrapper version 2.2.13 then stepping back one librealsense SDK version earlier to **2.33.1** may be an option, as that SDK can also be matched with ROS wrapper 2.2.13. 

I also note in your log that **align_depth** is set to True.  If you do not need to align depth to color in your ROS project then setting that option to False may free up some processing.

**Comment by ivelso** [comment]
Thank you @MartyG-RealSense    I will try to update the library and see if that helps as I am getting heaps of the error about the time. Will i need to change my launch file for the turtlebot if I update to the newest version of librealsense SDK?

**Comment by MartyG-RealSense** [comment]
If you are using RealSense ROS, updating librealsense versions involves matching that SDK to the ROS wrapper version that is most closely matched to that SDK version.  This information is on the ROS wrapper **Releases** page for each wrapper version.  For example, it is recommended that librealsense SDK **2.38.1** is matched with ROS wrapper version **2.2.17** if using ROS Kinetic or Melodic.

https://github.com/IntelRealSense/realsense-ros/releases

In regard to launch settings, they remain consistent over the long term even when new ROS wrapper versions or librealsense versions are introduced.  Bear in mind though that from wrapper version **2.2.15** onward, the infra, IMU and fisheye are set to False by default, so you should enable these by setting them to True if you need them (either in the roslaunch instruction or within the launch file) if you are using these more recent ROS wrapper versions.

**Comment by ivelso** [comment]
I updated the library and the wrapper. getting error that "running with a different librealsense version than the one the wrapper was compiled with! " but it works. 
The camera is still loosing images even when the image rate is 15fps. 
Do you have any other suggestions to improve it? 
I am currently using the aligned_depth_to_color 


turtlebot07@turtlebot07:~$ roslaunch turtlebot3_bringup turtlebot3_robot.launch 
... logging to /home/turtlebot07/.ros/log/ac08a30e-fe04-11ea-854c-0800274146ea/roslaunch-turtlebot07-2532.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.0.17:43533/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 30
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -1.0
 * /camera/realsense2_camera/color_fps: 15
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 15
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 15
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 30
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 15
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: camera/odom_in
 * /camera/realsense2_camera/unite_imu_method: none
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /turtlebot3_core/baud: 115200
 * /turtlebot3_core/port: /dev/ttyACM0
 * /turtlebot3_core/tf_prefix: 
 * /turtlebot3_lds/frame_id: base_scan
 * /turtlebot3_lds/port: /dev/ttyUSB0

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)
  /
    turtlebot3_core (rosserial_python/serial_node.py)
    turtlebot3_diagnostics (turtlebot3_bringup/turtlebot3_diagnostics)
    turtlebot3_lds (hls_lfcd_lds_driver/hlds_laser_publisher)

ROS_MASTER_URI=http://192.168.0.112:11311

process[turtlebot3_core-1]: started with pid [2541]
process[turtlebot3_lds-2]: started with pid [2542]
process[camera/realsense2_camera_manager-3]: started with pid [2543]
process[camera/realsense2_camera-4]: started with pid [2544]
process[turtlebot3_diagnostics-5]: started with pid [2545]
[ INFO] [1600910666.978346472]: Initializing nodelet with 4 worker threads.
[ INFO] [1600910667.160377911]: RealSense ROS v2.2.17
[ INFO] [1600910667.160423174]: Built with LibRealSense v2.33.1
[ INFO] [1600910667.160450554]: Running with LibRealSense v2.38.1
[ WARN] [1600910667.160477253]: ***************************************************
[ WARN] [1600910667.160495768]: ** running with a different librealsense version **
[ WARN] [1600910667.160515645]: ** than the one the wrapper was compiled with!   **
[ WARN] [1600910667.160534978]: ***************************************************
[INFO] [1600910667.246841]: ROS Serial Python Node
[INFO] [1600910667.336965]: Connecting to /dev/ttyACM0 at 115200 baud
[ INFO] [1600910667.377927535]:  
[ INFO] [1600910667.381926278]: Device with serial number 841612071764 was found.

[ INFO] [1600910667.381978096]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-4/2-4:1.0/video4linux/video0 was found.
[ INFO] [1600910667.382031573]: Device with name Intel RealSense D435I was found.
[ INFO] [1600910667.382603458]: Device with port number 2-4 was found.
[ INFO] [1600910667.524315777]: getParameters...
[INFO] [1600910669.477112]: Note: publish buffer size is 1024 bytes
[INFO] [1600910669.477516]: Setup publisher on sensor_state [turtlebot3_msgs/SensorState]
[INFO] [1600910669.491251]: Setup publisher on firmware_version [turtlebot3_msgs/VersionInfo]
[INFO] [1600910669.511260]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1600910669.530473]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[INFO] [1600910669.547896]: Setup publisher on odom [nav_msgs/Odometry]
[INFO] [1600910669.577678]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1600910669.594410]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1600910669.613471]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1600910670.064835]: Setup publisher on /tf [tf/tfMessage]
[INFO] [1600910670.122811]: Note: subscribe buffer size is 1024 bytes
[INFO] [1600910670.123283]: Setup subscriber on cmd_vel [geometry_msgs/Twist]
[INFO] [1600910670.175675]: Setup subscriber on joint_trajectory_point [std_msgs/Float64MultiArray]
[INFO] [1600910670.209664]: Setup subscriber on joint_move_time [std_msgs/Float64]
[INFO] [1600910670.279482]: Setup subscriber on gripper_position [std_msgs/Float64MultiArray]
[INFO] [1600910670.324010]: Setup subscriber on gripper_move_time [std_msgs/Float64]
[INFO] [1600910670.371279]: Setup subscriber on sound [turtlebot3_msgs/Sound]
[INFO] [1600910670.436751]: Setup subscriber on motor_power [std_msgs/Bool]
[INFO] [1600910670.470242]: Setup subscriber on reset [std_msgs/Empty]
[INFO] [1600910672.622819]: Setup TF on Odometry [odom]
[INFO] [1600910672.624585]: Setup TF on IMU [imu_link]
[INFO] [1600910672.626374]: Setup TF on MagneticField [mag_link]
[INFO] [1600910672.628143]: Setup TF on JointState [base_link]
[INFO] [1600910672.640728]: --------------------------
[INFO] [1600910672.642423]: Connected to OpenCR board!
[INFO] [1600910672.644423]: This core(v2.0.1) is compatible with TB3 with OpenManipulator
[INFO] [1600910672.646402]: --------------------------
[INFO] [1600910672.648092]: Start Calibration of Gyro
[ INFO] [1600910675.037833584]: setupDevice...
[ INFO] [1600910675.037885382]: JSON file is not provided
[ INFO] [1600910675.037905404]: ROS Node Namespace: camera
[ INFO] [1600910675.037945944]: Device Name: Intel RealSense D435I
[ INFO] [1600910675.038009299]: Device Serial No: 841612071764
[ INFO] [1600910675.038053415]: Device physical port: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-4/2-4:1.0/video4linux/video0
[ INFO] [1600910675.038098847]: Device FW version: 05.12.07.100
[ INFO] [1600910675.038148097]: Device Product ID: 0x0B3A
[ INFO] [1600910675.038180776]: Enable PointCloud: Off
[ INFO] [1600910675.038207744]: Align Depth: On
[ INFO] [1600910675.038233246]: Sync Mode: On
[ INFO] [1600910675.038294720]: Device Sensors: 
[ INFO] [1600910675.042071360]: Stereo Module was found.
[ INFO] [1600910675.051565501]: RGB Camera was found.
[ INFO] [1600910675.051908066]: Motion Module was found.
[ INFO] [1600910675.051977544]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1600910675.052034460]: num_filters: 0
[ INFO] [1600910675.052059468]: Setting Dynamic reconfig parameters.
[INFO] [1600910675.190641]: Calibration End
[ WARN] [1600910675.479903582]: This firmware(v2.0.1) isn't compatible with this software (v1.2.3)
[ WARN] [1600910675.479982705]: You can find how to update its in `FAQ` section(turtlebot3.robotis.com)
[ INFO] [1600910677.644762443]: Done Setting Dynamic reconfig parameters.
[ INFO] [1600910677.645546644]: depth stream is enabled - width: 640, height: 480, fps: 15, Format: Z16
[ INFO] [1600910677.646320623]: color stream is enabled - width: 640, height: 480, fps: 15, Format: RGB8
[ INFO] [1600910677.647974054]: setupPublishers...
[ INFO] [1600910677.733595907]: Expected frequency for depth = 15.00000
[ INFO] [1600910679.518583725]: Expected frequency for color = 15.00000
[ INFO] [1600910681.507173938]: Expected frequency for aligned_depth_to_color = 15.00000
[ INFO] [1600910683.196819570]: setupStreams...
[ INFO] [1600910683.197338642]: insert Depth to Stereo Module
[ INFO] [1600910683.197412905]: insert Color to RGB Camera
[ INFO] [1600910683.205097863]: SELECTED BASE:Depth, 0
[ INFO] [1600910683.974963251]: RealSense Node Is Up!

**Comment by MartyG-RealSense** [comment]
I believe that the version error message would be corrected by rebuilding the ROS wrapper **2.2.17** with the SDK **2.38.1** that you already have installed (i.e don't rebuild librealsense, just the RealSense ROS wrapper).  I would guess that the error was caused by building the 2.2.17 wrapper with SDK 2.33.1 installed and then upgrading the SDK version to 2.38.1 afterwards?

Simply building the wrapper again with 2.38.1 installed may make a difference.  I would also suggest adding the command below to your roslaunch instruction to see whether it helps.  It will perform a reset of the camera.

**initial_reset:=true**

**Comment by MartyG-RealSense** [comment]
Hi @ivelso   Do you still require assistance with this case, please?  Thanks!

**Comment by ivelso** [comment]
Hi @MartyG-RealSense,  I am not able to remove the error of the camera that it is compiled with a different wrapper. I have tried  
$ cd ~/catkin_ws
$ catkin_make
and 
$ catkin clean

but the error is not removed. 

Also the camera performance is not improved. The camera does not crash, but I still do not get images every second. It can go a few seconds between each image containing rgb image and depth image with the same timestamp. The setting for sending images with the same timestamp is on.  

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 30
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -1.0
 * /camera/realsense2_camera/color_fps: 15
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 15
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 15
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 30
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 15
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: camera/odom_in
 * /camera/realsense2_camera/unite_imu_method: none
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /turtlebot3_core/baud: 115200
 * /turtlebot3_core/port: /dev/ttyACM0
 * /turtlebot3_core/tf_prefix: 
 * /turtlebot3_lds/frame_id: base_scan
 * /turtlebot3_lds/port: /dev/ttyUSB0

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)
  /
    turtlebot3_core (rosserial_python/serial_node.py)
    turtlebot3_diagnostics (turtlebot3_bringup/turtlebot3_diagnostics)
    turtlebot3_lds (hls_lfcd_lds_driver/hlds_laser_publisher)

ROS_MASTER_URI=http://192.168.0.112:11311

process[turtlebot3_core-1]: started with pid [8525]
process[turtlebot3_lds-2]: started with pid [8526]
process[camera/realsense2_camera_manager-3]: started with pid [8527]
process[camera/realsense2_camera-4]: started with pid [8528]
process[turtlebot3_diagnostics-5]: started with pid [8532]
[ INFO] [1601625484.398046345]: Initializing nodelet with 4 worker threads.
[INFO] [1601625484.608400]: ROS Serial Python Node
[ INFO] [1601625484.617051926]: RealSense ROS v2.2.17
[ INFO] [1601625484.617153138]: Built with LibRealSense v2.33.1
[ INFO] [1601625484.617232188]: Running with LibRealSense v2.38.1
[ WARN] [1601625484.617325731]: ***************************************************
[ WARN] [1601625484.617415957]: ** running with a different librealsense version **
[ WARN] [1601625484.617491747]: ** than the one the wrapper was compiled with!   **
[ WARN] [1601625484.617720917]: ***************************************************
[INFO] [1601625484.723156]: Connecting to /dev/ttyACM0 at 115200 baud
[ INFO] [1601625484.922183282]:  
[ INFO] [1601625484.932162498]: Device with serial number 841612071764 was found.

**Comment by MartyG-RealSense** [comment]
The next action that I would recommend trying is to set **enable_sync** to False.  This option is not related to depth to color alignment, but instead it "gathers closest frames of different sensors, infrared, color and depth, to be sent with the same timetag".  In most cases that I see, this option is listed as False in the ROS launch log.

**Comment by MartyG-RealSense** [comment]
Hi @ivelso   Do you still require assistance with this case, please?   Thanks!

**Comment by ivelso** [comment]
Hi @MartyG-RealSense .  Removing the enable_sync will not send the images with same time stamp making my control not thrust them as I want to ensure that they match in order to find the object and get the distance to the object. If this is not the same it is a chance that the distance is incorrect when the robot is turning. The stream is relatively stable and works good enough for my application now. Thank you for the help.

**Comment by MartyG-RealSense** [comment]
Thanks very much for the update @ivelso
