### ISSUE TITLE
How to start camera node with yaml file?

### ISSUE THREAD

**Issue by WundtAsim** [realsenseai/realsense-ros#2900]
# environment
ubuntu2204
ROS2 humble
distro:`sudo apt install ros-humble-realsense2-*`
# question
I tried:
```
ros2 launch realsense2_camera rs_launch.py config_file:="/home/yangqi/.realsense/config.yaml"
```
The content of the 'config.yaml':
```
enable_color: true
enable_sync: true
rgb_camera.profile: 1280x720x30
depth_module.profile: 1280x720x30
depth_module.enable_auto_exposure: true
enable_depth: true
align_depth.enable: true

publish_tf: true
tf_publish_rate: 1.0

pointcloud.enable: true
decimation_filter,enable: true
spatial_filter.enable: true
temporal_filter.enable: true
disparity_filter.enable: true
```
the output of terminal is:
```
[INFO] [launch]: All log files can be found below /home/yangqi/.ros/log/2023-10-08-18-07-39-706370-PC-45691
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [realsense2_camera_node-1]: process started with pid [45692]
[realsense2_camera_node-1] [INFO] [1696759660.023251414] [camera.camera]: RealSense ROS v4.54.1
[realsense2_camera_node-1] [INFO] [1696759660.023329198] [camera.camera]: Built with LibRealSense v2.54.1
[realsense2_camera_node-1] [INFO] [1696759660.023341533] [camera.camera]: Running with LibRealSense v2.54.1
[realsense2_camera_node-1] [INFO] [1696759660.035028812] [camera.camera]: Device with serial number 308322060611 was found.
[realsense2_camera_node-1] 
[realsense2_camera_node-1] [INFO] [1696759660.035078908] [camera.camera]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/video4linux/video0 was found.
[realsense2_camera_node-1] [INFO] [1696759660.035088875] [camera.camera]: Device with name Intel RealSense D415 was found.
[realsense2_camera_node-1] [INFO] [1696759660.035248225] [camera.camera]: Device with port number 2-3 was found.
[realsense2_camera_node-1] [INFO] [1696759660.035259953] [camera.camera]: Device USB type: 3.2
[realsense2_camera_node-1] [INFO] [1696759660.036343026] [camera.camera]: getParameters...
[realsense2_camera_node-1] [WARN] [1696759660.036492318] [camera.camera]: Publishing dynamic camera transforms (/tf) at 1 Hz
[realsense2_camera_node-1] [INFO] [1696759660.036849200] [camera.camera]: JSON file is not provided
[realsense2_camera_node-1] [INFO] [1696759660.036864743] [camera.camera]: Device Name: Intel RealSense D415
[realsense2_camera_node-1] [INFO] [1696759660.036873287] [camera.camera]: Device Serial No: 308322060611
[realsense2_camera_node-1] [INFO] [1696759660.036881183] [camera.camera]: Device physical port: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/video4linux/video0
[realsense2_camera_node-1] [INFO] [1696759660.036889353] [camera.camera]: Device FW version: 5.15.1
[realsense2_camera_node-1] [INFO] [1696759660.036896870] [camera.camera]: Device Product ID: 0x0AD3
[realsense2_camera_node-1] [INFO] [1696759660.036905863] [camera.camera]: Sync Mode: On
[realsense2_camera_node-1] [INFO] [1696759660.058392218] [camera.camera]: Set Exposure.1 to 7500
[realsense2_camera_node-1] [INFO] [1696759660.081797220] [camera.camera]: Stopping Sensor: Depth Module
[realsense2_camera_node-1] [INFO] [1696759660.084185649] [camera.camera]: Starting Sensor: Depth Module
[realsense2_camera_node-1] [INFO] [1696759660.094407904] [camera.camera]: Open profile: stream_type: Depth(0), Format: Z16, Width: 1280, Height: 720, FPS: 30
[realsense2_camera_node-1] [INFO] [1696759660.094518047] [camera.camera]: Stopping Sensor: RGB Camera
[realsense2_camera_node-1] [INFO] [1696759660.105195693] [camera.camera]: Starting Sensor: RGB Camera
[realsense2_camera_node-1] [INFO] [1696759660.108384502] [camera.camera]: Open profile: stream_type: Color(0), Format: RGB8, Width: 1280, Height: 720, FPS: 30
[realsense2_camera_node-1] [INFO] [1696759660.109364361] [camera.camera]: RealSense Node Is Up!
```
While, there is nothing in rviz2:
![Screenshot from 2023-10-08 18-11-45](https://github.com/IntelRealSense/realsense-ros/assets/55453182/9fcaf6b0-d2a7-4c18-9d80-7cbab804d6bd)

By the way, this works fine: `ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true align_depth.enable:=true`

**Comment by MartyG-RealSense** [comment]
Hi @WundtAsim  The best reference available for using a yaml configuration file with ROS2 is at https://github.com/IntelRealSense/realsense-ros/issues/1640 and lists the contents of the yaml file.

That case related to the previous ROS2 wrapper (now called **ros2-legacy**) rather than the current 4.54.1 wrapper but the case may contain useful insights.

**Comment by WundtAsim** [comment]
Hi @MartyG-RealSense  
Thanks for your quick answer. I tested my YAML file and got a conclusion:
after I delete this line: `disparity_filter.enable: true`, I got the right pointcloud in rviz.
a little confused...
anyway, my problem has been solved, but I do think there should be better documentation about how to use the parameters in yaml file.
Thanks for your help.

**Comment by MartyG-RealSense** [comment]
You are very welcome!

**Comment by MartyG-RealSense** [comment]
Case closed due to solution achieved and no further comments received.

**Comment by liushuya7** [comment]
I still have issue launching the realsense camera with yaml file. It was working with ros2-legacy branch, but not working with the ros2-master branch.

From `rs_launch.py`
```py
def yaml_to_dict(path_to_yaml):
    with open(path_to_yaml, "r") as f:
        return yaml.load(f, Loader=yaml.SafeLoader)

def launch_setup(context, params, param_name_suffix=''):
    _config_file = LaunchConfiguration('config_file' + param_name_suffix).perform(context)
    params_from_file = {} if _config_file == "''" else yaml_to_dict(_config_file)

    _output = LaunchConfiguration('output' + param_name_suffix)
    if(os.getenv('ROS_DISTRO') == 'foxy'):
        # Foxy doesn't support output as substitution object (LaunchConfiguration object)
        # but supports it as string, so we fetch the string from this substitution object
        # see related PR that was merged for humble, iron, rolling: https://github.com/ros2/launch/pull/577
        _output = context.perform_substitution(_output)

    return [
        launch_ros.actions.Node(
            package='realsense2_camera',
            namespace=LaunchConfiguration('camera_namespace' + param_name_suffix),
            name=LaunchConfiguration('camera_name' + param_name_suffix),
            executable='realsense2_camera_node',
            parameters=[params, params_from_file], #<----- HERE
            output=_output,
            arguments=['--ros-args', '--log-level', LaunchConfiguration('log_level' + param_name_suffix)],
            emulate_tty=True,
            )
    ]

def generate_launch_description():
    return LaunchDescription(declare_configurable_parameters(configurable_parameters) + [
        OpaqueFunction(function=launch_setup, kwargs = {'params' : set_configurable_parameters(configurable_parameters)})
    ])
```
My speculation is that the string object can't overwrite the LaunchConfiguration object. When I print out the parameters, the `params_from_file` is a dictionary of strings whereas the params is a dictionary of `launch.substitutions.launch_configuration.LaunchConfiguration object`.

**Comment by MartyG-RealSense** [comment]
Hi @liushuya7  The current ros2-master ROS2 wrapper provides a tutorial for using a yaml file with it at the link below, with a demo launch file called `rs_launch_get_params_from_yaml.py`

https://github.com/IntelRealSense/realsense-ros/tree/ros2-master/realsense2_camera/examples/launch_params_from_file
